### PR TITLE
Check that code conforms to rustfmt formatting

### PR DESCRIPTION
**Pull request by baumanj**

### CODE REVIEW

**Comment by kinetiknz** [comment]
LGTM, thanks.

**Comment by ChunMinChang** [comment]
BTW, `rustfmt` is not always available with _Rust Nightly_. The availability can be checked [here](https://rust-lang.github.io/rustup-components-history/).

When the `rustfmt` is unavailable in current _Rust Nightly_, it needs to install the latest available `rustfmt` to make `cargo fmt` work. Here is an [example](https://github.com/rust-lang/rust-clippy/blob/27acea0a1baac6cf3ac6debfdbce04f91e15d772/.travis.yml#L40-L46). 

Mmore detail can be found in [here](https://github.com/rust-lang/rustup-components-history/blob/master/README.md)

**Comment by baumanj** [comment]
Maybe it would be easier to only do the check on stable? I need to fix an issue anyway since
```bash
cargo fmt -- --check || echo "some error message"
```
will always succeed due to the exit status of `echo`.

**Comment by kinetiknz** [comment]
> BTW, `rustfmt` is not always available with _Rust Nightly_. The availability can be checked [here](https://rust-lang.github.io/rustup-components-history/).

That's a trap, thanks for the heads up!

> Maybe it would be easier to only do the check on stable?

Sounds good.

**Comment by baumanj** [comment]
Fixes over here: https://github.com/mozilla/mp4parse-rust/pull/207

**Pull request merged**
