### PR TITLE
Bump env_logger and num-traits

### PR DESCRIPTION
**Pull request by linkmauve**
The latter is required by https://github.com/image-rs/image/pull/1398

### CODE REVIEW

**Comment by baumanj** [comment]
Thanks for the submission!

**Comment by linkmauve** [comment]
Hi, could you do a release with this change?  This is blocking https://github.com/image-rs/image/pull/1398 from being merged.

**Comment by baumanj** [comment]
Sure, I'll try to get around to that shortly. Just to clarify, it's a crates.io release you need, not just a release on the Github repo, correct?

**Comment by linkmauve** [comment]
Correct. :)

**Comment by baumanj** [comment]
Ok, both https://crates.io/crates/mp4parse and https://crates.io/crates/mp4parse_capi should be on 0.11.5 now. Let me know if there's anything else you need.

**Pull request merged**
