### PR TITLE
Bump version to 0.7.1

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by nox** [comment]
Please merge and publish this.

**Comment by rillian** [comment]
I'm still unclear on some aspects of semver. Any reason you didn't bump the mp4parse_capi crate too?

**Comment by rillian** [comment]
I bumped and published separately in a422808043e6a21ee98729dd8bfe1e8234897d18.

**Comment by nox** [comment]
There was no need to bump `mp4parse_capi` because it depended on `mp4parse` 0.7 which is compatible with 0.7.1.

**Pull request closed without merging**
