### PR TITLE
Disable the ahash-compile-time-rng feature of hashbrown that makes bu…

### PR DESCRIPTION
**Pull request by glandium**
…ilds unreproducible.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1637140

### CODE REVIEW

**Comment by kinetiknz** [comment]
LGTM, thanks!

Looks like this is also [fixed](https://github.com/rust-lang/hashbrown/commit/8858039cfa74443e49c364bd9932de5d418ffcac#diff-80398c5faae3c069e4e6aa2ed11b28c0) upstream in 0.7.2.

**Comment by glandium** [comment]
Oh! So we actually don't need this, we can just update to hashbrown 0.7.2 in Firefox!

**Comment by kinetiknz** [comment]
> Oh! So we actually don't need this, we can just update to hashbrown 0.7.2 in Firefox!

Sounds good, would you like me to revert this PR now?

**Comment by glandium** [comment]
I don't have a preference.

**Pull request merged**
