### PR TITLE
Check ipma validity and preallocate associations vec

### PR DESCRIPTION
**Pull request by baumanj**
This fixes a timeout with [the attached testcase](https://github.com/mozilla/mp4parse-rust/files/5491742/clusterfuzz-testcase-minimized-avif-5139142796902400.zip) run against the `mp4parse_capi` crate with:
```
cargo +nightly fuzz run avif clusterfuzz-testcase-minimized-avif-5139142796902400 -- -timeout=60
```
Resolves https://oss-fuzz.com/testcase-detail/5139142796902400

### CODE REVIEW

**Review by SingingTree — APPROVED** [review]
LGTM. It would be useful to me when reading the code to have a comment around the new block saying something along the lines of "verify size of box is sane given parameters" + "done verifying sanity of box" so I know I can skip this block if I'm assuming happy path.

Edit: something like "check validity" then "got valid size, per-allocate" would be good too. I'll stop bikeshedding the wording :) Ping me if there's anything further I can help look over.

**Comment by baumanj** [comment]
> LGTM. It would be useful to me when reading the code to have a comment around the new block saying something along the lines of "verify size of box is sane given parameters" + "done verifying sanity of box" so I know I can skip this block if I'm assuming happy path.

That's a good idea. In fact, I think I'll break it out into a separate function to make that totally clear. Will update this likely tomorrow.

> Ping me if there's anything further I can help look over.

I originally made all the arithmetic use the `checked_XXX` functions instead of regular operators, but I found that harder to read, and considering most of it can be proven to make overflow/div-by-zero impossible, I'd appreciate you validating that as well to be sure I'm not missing anything. Worst case, we crash since [we have overflow checks on](https://github.com/mozilla/mp4parse-rust/blob/master/Cargo.toml#L8), but I'd still prefer to avoid that.

**Comment by SingingTree** [comment]
> 
> I originally made all the arithmetic use the `checked_XXX` functions instead of regular operators, but I found that harder to read, and considering most of it can be proven to make overflow/div-by-zero impossible, I'd appreciate you validating that as well to be sure I'm not missing anything. Worst case, we crash since [we have overflow checks on](https://github.com/mozilla/mp4parse-rust/blob/master/Cargo.toml#L8), but I'd still prefer to avoid that.

I agree, I cannot see a way in the current code that we can overflow or divide by zero. Because this is based on a spec that is unlikely to blow us up by wildly widening a datatype (or changing anything, for that matter) I think this is good (if it were going to change a lot, maybe bite the bullet and use checked arithmetic to save on us hand checking each time). We could add a comment saying 'if changing this code please verify that is cannot overflow or divide by zero' as another barrier.

**Comment by baumanj** [comment]
I was interested to see if I could get the compiler to validate that none of the arithmetic could overflow, and I think I was successful. This may be a bit overkill, but since this sort of validation keeps coming up in fuzzing, I think this may be of broader use in future work.

**Review by SingingTree — APPROVED** [review]

**Pull request merged**
